runtime: python39

instance_class: F2

env_variables:
  STREAMLIT_SERVER_PORT: 8080
  STREAMLIT_SERVER_HEADLESS: true
  STREAMLIT_SERVER_ENABLE_CORS: true
  STREAMLIT_BROWSER_GATHER_USAGE_STATS: false
  STREAMLIT_THEME_PRIMARY_COLOR: "#4682b4"

handlers:
- url: /.*
  script: auto
  secure: always

automatic_scaling:
  min_instances: 0
  max_instances: 2
  min_idle_instances: 0
  max_idle_instances: 1
  min_pending_latency: automatic
  max_pending_latency: automatic
  target_cpu_utilization: 0.65
  target_throughput_utilization: 0.65

inbound_services:
- warmup
