[theme]
primaryColor = "#4682b4"  # Steel blue
backgroundColor = "#1e2630"  # Dark background similar to the image
secondaryBackgroundColor = "#2d3741"  # Slightly lighter than background
textColor = "#ffffff"  # White text for dark background
font = "sans-serif"

[server]
enableCORS = true
enableXsrfProtection = true
maxUploadSize = 50
maxMessageSize = 100

[browser]
gatherUsageStats = false

[runner]
# Enable memory profiling to optimize performance
magicEnabled = true
installTracer = false
fixMatplotlib = true

[logger]
level = "info"
messageFormat = "%(asctime)s %(levelname)s: %(message)s"
